package pl.edu.pw.elka.polishentitylinker.flow;

public enum ProgramOption {
    IMPORT_WIKI_ITEMS,
    IMPORT_PAGES,
    IMPORT_REDIRECTS,
    LINK_ENTITIES,
    SANITIZE_CORPUS,
    SANITIZE_DIRECTORY_CORPUS,
    PROCESS_CORPUS,
    MERGE_DIVIDED_CORPUS,
    EXTRACT_ARTICLES,
    PREPARE_TRAIN_TEST,
    PROCESS_CATEGORIES,
    PREPARE_TUNE_DATASET
}
